EDashboard/Controllers/DeviceController.cs
using EDashboard.Models;
using EDashboard.Models.BAL;
using EDashboard.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EDashboard.Controllers
{
    public class DeviceController : Controller
    {
        // GET: Device
        [MyAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        DeviceMessageBusiness objMsg = new DeviceMessageBusiness();
        public ActionResult DeviceMessges(HPDeviceDetails model)
        {
            return Json(objMsg.GetAllMessages(model));
        }

        public ActionResult GetNotificationCount(HPDeviceDetails model)
        {
            return Json(objMsg.GetNotificationCount());
        }
    }
}

EDashboard/Controllers/DeviceRegistrationController.cs
using EDashboard.Models;
using EDashboard.Models.BAL;
using EDashboard.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EDashboard.Controllers
{
    public class DeviceRegistrationController : Controller
    {
        // GET: DeviceRegistration
        [MyAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        DeviceMessageBusiness objMsg = new DeviceMessageBusiness();
        public ActionResult GetDeviceList(Device model)
        {
            return Json(objMsg.Get_DeviceList(model));
        }

        public ActionResult InsertDevice(Device model)
        {
            return Json(objMsg.InsertDevice(model));
        }
    }
}

EDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>DeskApp Dashboard</title>
    <!-- Site favicon -->
    <!-- <link rel="shortcut icon" href="images/favicon.ico"> -->
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- CSS -->
    @Styles.Render("~/Content/AdminPanel/Style.css")
</head>
<body data-ng-app="EDashboard">
    
    <div class="header clearfix">
        <div class="header-right">
            <div class="brand-logo">
                <a href="index.php">
                    <img src="@Url.Content("~/Content/images/hmillogo.png")" alt="" class="mobile-logo">
                </a>
            </div>
            <div class="menu-icon">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="user-info-dropdown">
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                        <span class="user-icon"><i class="fa fa-user-o"></i></span>
                        <span class="user-name">Johnny Brown</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="profile.php"><i class="fa fa-user-md" aria-hidden="true"></i> Profile</a>
                        <a class="dropdown-item" href="profile.php"><i class="fa fa-cog" aria-hidden="true"></i> Setting</a>
                        <a class="dropdown-item" href="faq.php"><i class="fa fa-question" aria-hidden="true"></i> Help</a>
                        <a class="dropdown-item" href="login.php"><i class="fa fa-sign-out" aria-hidden="true"></i> Log Out</a>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <div class="left-side-bar">
        <div class="brand-logo">
            <a href="index.php">
                <img src="@Url.Content("~/Content/images/hmillogo.png")" alt="">
            </a>
        </div>
        <div class="menu-block customscroll">
            <div class="sidebar-menu">
                <ul id="accordion-menu">
                    <li>
                        <a href="@Url.Action("Index","DeviceRegistration")" class="dropdown-toggle">
                            <span class="fa fa-home"></span><span class="mtext">Device Master</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Device")" class="dropdown-toggle">
                            <span class="fa fa-home"></span><span class="mtext">Dashboard</span>
                        </a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()

    @Scripts.Render("~/Scripts/AdminPanel/jquery-2.2.3.min.js")
    @Scripts.Render("~/Scripts/AdminPanel/bootstrap.min.js")
    @Scripts.Render("~/Scripts/AdminPanel/angular.min.js")
    @Scripts.Render("~/Scripts/AdminPanel/App.js")
    @Scripts.Render("~/Scripts/AdminPanel/common.js")
    @Scripts.Render("~/Scripts/AdminPanel/ShowCustomAlert.js")
    @Scripts.Render("~/Scripts/AdminPanel/script.js")
    @Scripts.Render("~/Scripts/AdminPanel/vmenu.js")
    @Scripts.Render("~/Scripts/AdminPanel/DeviceMasterController.js")
    @Scripts.Render("~/Scripts/AdminPanel/DeviceController.js")
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>